### PR TITLE
Mounting holes: add refdes and oblong holes

### PR DESCRIPTION
**Pull request by evanshultz**
Not seeing any action at https://github.com/KiCad/Mounting_Holes.pretty/pull/5, I'm resubmitting these footprints.
pad_oval
pad_oval_via

I also added the refdes on F.Fab as Oliver requested in the linked PR.

### CODE REVIEW

**Comment by evanshultz** [comment]
KLC violations with annular ring size fixed. It doesn't change the board after Gerber, but doesn't hurt to eliminate this KLC violation. The existing KLC violations for no elements on the fab layer and no 3D model are OK, as I understand it.

**Comment by evanshultz** [comment]
Can I get a review, please?

**Comment by SchrodingersGat** [comment]
I think that these footprints should be marked as "Virtual" rather than "through hole"? They are not actually to be loaded onto a PCB...

**Comment by evanshultz** [comment]
@SchrodingersGat Is this good? I changed all of them to Virtual. I don't really understand this, but it seems to have no effect on the board, 3D viewer, or outputs.

**Comment by SchrodingersGat** [comment]
Hi @evanshultz `virtual` footprints are those which do not actually have a component associated with them.  e.g. a mounting hole does not get loaded onto the PCB.

The `surface mount` and `through hole` attributes are used to determine which components get loaded in SMT assembly or THT placement. Virtual components do not get loaded in either.

**Comment by evanshultz** [comment]
@SchrodingersGat I assumed this, but what I don't understand is how that works for mounting holes with a net connection. However, I used a testpoint symbol and selected one of these Virtual mounting holes and it all worked out OK in the PCB, so I guess this is fine. Just weird that these Virtual parts may, in some cases, be connected to a net and in other cases not connected to anything.

**Pull request merged**
