### PR TITLE
Add oval hole variation (4.3x6.2mm) for M4

### PR DESCRIPTION
**Pull request by pointhi**
pad_oval
pad_oval_via

### CODE REVIEW

**Comment by evanshultz** [comment]
@SchrodingersGat Is there a reason why Travis isn't running on this PR? I know this repo is for simple footprints, but it seems to me Travis should still do his thing.

**Comment by SchrodingersGat** [comment]
I shall poke him - perhaps he is asleep

**Comment by evanshultz** [comment]
@SchrodingersGat Wonder why he didn't wake up when I closed and re-opened...

@pointhi See the results from Travis. Some are due to KLC changing since these footprints were made.

**Comment by SchrodingersGat** [comment]
He wasn't watching this repository! I have to manually point him at each one, some get missed :)

**Comment by evanshultz** [comment]
@pointhi When will you be able to take a look at this PR?

**Comment by evanshultz** [comment]
@pointhi I'm assuming you don't care to finish off this PR.

@SchrodingersGat Do you want these footprints in the library? I'll open a new PR then. If not, please close the case or let me know and I'll do it.

**Comment by SchrodingersGat** [comment]
Yes it is probably worth adding them! At some stage (in the future) I would like to develop a better scheme for mounting holes / wire pads etc. But if you want to add these as a PR for now that's great :)

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks Oliver, I'll do that. Do mounting holes need 3D models and F.Fab refdes text? None of the others I see have it, but perhaps all our mounting holes are outdated.

**Comment by SchrodingersGat** [comment]
3D models wouldn't be required in general for these footprints. F.Fab refdes is always handy, though. It should be centered on the drill origin for the hole

**Comment by pointhi** [comment]
Merged in #6

**Pull request closed without merging**
