### PR TITLE
Major rework of mounting holes

### PR DESCRIPTION
**Pull request by twam**
Added mounting holes for ISO metric screws.
Added mounting holes with screw sizes in Cmts.User layer for DIN965, ISO14580 and ISO7380.
Replaced german descriptions with english ones.
Added mounting holes versions with pads.
Added court yards to comply with Kicad Library Convention.

### CODE REVIEW

**Comment by pointhi** [comment]
hy @twam, greate work.
- In my opinion, improving the name would be a good idea :
  For example: `MountingHole_2-2mm_M2` --> `MountingHole_2.2mm_M2`
  
  @CarlPoirier do you have reserves against using a point instead of a hyphen for point numbers? For me, I was wondering what `2-2mm` could probably mean
- `MountingHole_2-2mm_M2` and similar Mounting Holes without an annular should use NTPH Pad instead. Or is it wanted to have the drilling of the holes always plated?

**Comment by twam** [comment]
I'd be happy to rename all the footprints and change the mounting holes without a connection to a NTPH pad.

I did the current naming/pads on purpose to enhance the lib in its current style. :)

**Comment by pointhi** [comment]
I think you can apply the suggested improvements. I don't think there are reseves against a more readable naming scheme (espcially because only one character is changed)

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
